default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  port: 3306
  host: localhost

development:
  <<: *default
  database: pong_matcher_rails_development

test:
  <<: *default
  database: pong_matcher_rails_test
